CREATE TABLE comments
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_of_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    text             TEXT,
    username         VARCHAR(255),
    news_id          BIGINT NOT NULL
);