CREATE TABLE news
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_of_creation TIMESTAMP default CURRENT_TIMESTAMP,
    title            VARCHAR(255),
    text             TEXT
);